# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "inception-terragrunt-test-poc"
    dynamodb_table = "my-lock-table-1"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-west-1"
  }
}
